a=input("Enter fruit 1:")
b=input("Enter fruit 2:")
c=input("Enter fruit 3:")
d=input("Enter fruit 4:")
e=input("Enter fruit 5:")
f=input("Enter fruit 6:")
g=input("Enter fruit 7:")
print(a,b,c,d,e,f,g)                
q=[a,b,c,d,e,f,g]
print(q)
input("fruit in sorted order :/n")
q.sort()
print(q)
